import type { Metadata } from "next";
import "../globals.css";
import { Nunito } from "next/font/google"
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toast } from "@/components/Toaster";

const nunito = Nunito({
  subsets: ["latin"],
  variable: '--nunito',
  style: ["normal"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} font-medium`}>
        <Navbar />
        <div className="mx-20 my-5">
          {children}
        </div>
        <Footer />
        <Toast />
      </body>
    </html >
  );
}
